spring.application.name=speaknote-backend

spring.docker.compose.enabled=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server.address=0.0.0.0
server.port=8080

logging.level.org.example.speaknotebackend=DEBUG

# CORS
custom.cors.allowed-origin=http://34.64.112.111:3000
Access-Control-Allow-Credentials: true

spring.servlet.multipart.max-file-size=40MB
spring.servlet.multipart.max-request-size=40MB

# Google STT
# custom.pdf.allowed-origin=https://speaknote-ai2025.azurewebsites.net/pdf
# GOOGLE_APPLICATION_CREDENTIALS ??? ????? ????? ???? ?? ??
GOOGLE_APPLICATION_CREDENTIALS=/path/to/stt-credentials.json

custom.pdf.allowed-origin=http://34.64.112.111:8000/pdf

# AI ?? URL? ?? IP? ??
ai.server.url=http://34.64.112.111:8000/text
